//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public m_employee()
        {
            this.t_career = new HashSet<t_career>();
            this.t_license = new HashSet<t_license>();
        }
    
        public string emp_cd { get; set; }
        public string user_id { get; set; }
        public string password { get; set; }
        public sbyte user_level { get; set; }
        public string last_name { get; set; }
        public string first_name { get; set; }
        public string last_name_kn { get; set; }
        public string first_name_kn { get; set; }
        public string section_id { get; set; }
        public bool gender_cd { get; set; }
        public System.DateTime birth_date { get; set; }
        public System.DateTime emp_date { get; set; }
        public string mail { get; set; }
        public string mobile { get; set; }
        public string zip_code { get; set; }
        public string address_city { get; set; }
        public string address_block { get; set; }
        public string address_building { get; set; }
        public Nullable<int> railway_route_cd { get; set; }
        public string nearest_station { get; set; }
        public string final_education { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public Nullable<sbyte> deleted { get; set; }
    
        public virtual m_section m_section { get; set; }
        public virtual m_railway_route m_railway_route { get; set; }
        public virtual m_skillsheet_comment m_skillsheet_comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_career> t_career { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_license> t_license { get; set; }

        // When deleting records, just set DeleteDate to DateTime.Now()
        public DateTime DeleteDate { get; set; }
    }
}
